apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-django-deployment
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-container
        image: priyam14/django-app:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

